# Generated by Django 4.0.1 on 2022-03-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField()),
                ('min_amount', models.FloatField()),
                ('max_amount', models.FloatField()),
                ('state', models.BooleanField()),
                ('description', models.CharField(max_length=1000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('tiker', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('network_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FakeAd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=10000)),
                ('trade_number', models.IntegerField()),
                ('trade_amount', models.FloatField()),
                ('reg_date', models.DateField()),
                ('min_amount', models.FloatField()),
                ('max_amount', models.FloatField()),
                ('des', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=1000)),
                ('owner_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('cryptocurrency', models.CharField(max_length=100)),
                ('from_adr', models.CharField(max_length=2000)),
                ('to_adr', models.CharField(max_length=2000)),
                ('type', models.CharField(max_length=1000)),
                ('link', models.CharField(blank=True, max_length=10000, null=True)),
                ('flag', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('to_id', models.IntegerField()),
                ('state', models.CharField(max_length=1000)),
                ('usdt_amount', models.FloatField()),
                ('coin_amount', models.FloatField()),
                ('coin', models.CharField(blank=True, max_length=20000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('tg_id', models.CharField(blank=True, default=None, max_length=10000, primary_key=True, serialize=False)),
                ('limit', models.IntegerField()),
                ('current_limit', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('USDT_balance', models.FloatField(blank=True, default=0, null=True)),
                ('TRX_balance', models.FloatField(blank=True, default=0, null=True)),
                ('XLM_balance', models.FloatField(blank=True, default=0, null=True)),
                ('ADA_balance', models.FloatField(blank=True, default=0, null=True)),
                ('DOGE_balance', models.FloatField(blank=True, default=0, null=True)),
                ('MATIC_balance', models.FloatField(blank=True, default=0, null=True)),
                ('LUNA_balance', models.FloatField(blank=True, default=0, null=True)),
                ('DOT_balance', models.FloatField(blank=True, default=0, null=True)),
                ('AVAX_balance', models.FloatField(blank=True, default=0, null=True)),
                ('address_USDT', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_TRX', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_XLM', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_ADA', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_DOGE', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_MATIC', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_LUNA', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_DOT', models.CharField(blank=True, max_length=2000, null=True)),
                ('address_AVAX', models.CharField(blank=True, max_length=2000, null=True)),
                ('trade_amount', models.FloatField(blank=True, default=0, null=True)),
                ('trade_count', models.IntegerField(blank=True, default=0, null=True)),
                ('reg_date', models.DateField(blank=True)),
                ('state', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
